locations:
  0:
    world: 'world'
    x: -10.5
    y: -60.0
    z: -118.5
  1:
    world: 'world'
    x: -6.5
    y: -60.0
    z: -118.5
  2:
    world: 'world'
    x: -6.5
    y: -60.0
    z: -117.5
  3:
    world: 'world'
    x: -6.5
    y: -58.0
    z: -115.5
  4:
    world: 'world'
    x: -6.5
    y: -58.0
    z: -113.5
  5:
    world: 'world'
    x: -6.5
    y: -60.0
    z: -111.5
  6:
    world: 'world'
    x: -6.5
    y: -60.0
    z: -110.5
  7:
    world: 'world'
    x: -13.5
    y: -60.0
    z: -110.5
  8:
    world: 'world'
    x: -13.5
    y: -60.0
    z: -113.5
  9:
    world: 'world'
    x: -9.5
    y: -60.0
    z: -113.5
  10:
    world: 'world'
    x: -9.5
    y: -60.0
    z: -107.5
