locations:
  0:
    world: 'world'
    x: -5.5
    y: -60.0
    z: 8.5
  1:
    world: 'world'
    x: -5.5
    y: -60.0
    z: -12.5
  2:
    world: 'world'
    x: -2.5
    y: -60.0
    z: -7.5
  3:
    world: 'world'
    x: 0.5
    y: -60.0
    z: -12.5
  4:
    world: 'world'
    x: 0.5
    y: -60.0
    z: -7.5
  5:
    world: 'world'
    x: -3.5
    y: -60.0
    z: -7.5