locations:
  0:
    world: 'world'
    x: 10.5
    y: -60.0
    z: 1.5
  1:
    world: 'world'
    x: -2.5
    y: -60.0
    z: 1.5
  2:
    world: 'world'
    x: -2.5
    y: -60.0
    z: -7.5
  3:
    world: 'world'
    x: 2.5
    y: -60.0
    z: -2.5
  4:
    world: 'world'
    x: 10.5
    y: -60.0
    z: -2.5
  5:
    world: 'world'
    x: 10.5
    y: -60.0
    z: -7.5
  6:
    world: 'world'
    x: 6.5
    y: -60.0
    z: -7.5
  7:
    world: 'world'
    x: 6.5
    y: -60.0
    z: -0.5
  8:
    world: 'world'
    x: 10.5
    y: -60.0
    z: -0.5